# Generated by Django 6.0.3 on 2026-04-07 22:21

import apps.users.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('avatar', models.ImageField(blank=True, default='default-avatar.jpg', null=True, upload_to=apps.users.models.user_avatar_upload_to, verbose_name='Аватар')),
                ('signature', models.TextField(blank=True, verbose_name='Подпись')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('moderator', 'Модератор'), ('user', 'Пользователь')], default='user', max_length=20, verbose_name='Роль на форуме')),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последняя активность')),
                ('karma', models.IntegerField(default=0, verbose_name='Репутация')),
                ('notify_email_reply', models.BooleanField(default=True, verbose_name='Email при ответах в подписанных темах')),
                ('notify_email_mention', models.BooleanField(default=True, verbose_name='Email при @упоминании')),
                ('notify_email_pm', models.BooleanField(default=True, verbose_name='Email при личных сообщениях')),
                ('notify_email_moderation', models.BooleanField(default=True, verbose_name='Email о модерации (для модераторов)')),
                ('is_banned', models.BooleanField(default=False, verbose_name='Блокировка')),
                ('ban_reason', models.TextField(blank=True, verbose_name='Причина блокировки')),
                ('banned_until', models.DateTimeField(blank=True, null=True, verbose_name='Блокировка до (пусто = бессрочно)')),
                ('posting_suspended', models.BooleanField(default=False, help_text='Пользователь может входить, но не создавать темы и посты', verbose_name='Только чтение')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('ignored_users', models.ManyToManyField(blank=True, related_name='ignored_by', to=settings.AUTH_USER_MODEL, verbose_name='Игнорируемые пользователи')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
