# Generated by Django 6.0.3 on 2026-04-07 22:21

import apps.forum.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Описание')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('resolved', 'Приняты меры'), ('dismissed', 'Отклонена')], default='pending', max_length=20, verbose_name='Статус')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда рассмотрено')),
                ('moderator_note', models.TextField(blank=True, verbose_name='Заметка модератора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Жалоба',
                'verbose_name_plural': 'Жалобы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('reply', 'Ответ в теме'), ('mention', 'Упоминание'), ('pm', 'Личное сообщение'), ('mod', 'Модерация'), ('report', 'Жалоба')], max_length=20, verbose_name='Тип')),
                ('message', models.CharField(max_length=500, verbose_name='Текст')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='Ссылка')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='Вопрос')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст варианта')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Вариант опроса',
                'verbose_name_plural': 'Варианты опроса',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Голос в опросе',
                'verbose_name_plural': 'Голоса в опросах',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_removed', models.BooleanField(default=False, verbose_name='Удалено (мягко)')),
                ('removed_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда удалено')),
                ('removal_reason', models.CharField(blank=True, max_length=500, verbose_name='Причина удаления')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Скрыто модератором')),
                ('hidden_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда скрыто')),
                ('hidden_reason', models.CharField(blank=True, max_length=500, verbose_name='Причина скрытия')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.forum.models.post_attachment_upload_to, verbose_name='Файл')),
                ('original_name', models.CharField(max_length=255, verbose_name='Исходное имя')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
            },
        ),
        migrations.CreateModel(
            name='PostRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
                ('old_content', models.TextField(verbose_name='Было')),
                ('new_content', models.TextField(verbose_name='Стало')),
                ('edit_reason', models.CharField(blank=True, max_length=500, verbose_name='Причина правки')),
            ],
            options={
                'verbose_name': 'История правок сообщения',
                'verbose_name_plural': 'История правок сообщений',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrivateMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
            ],
            options={
                'verbose_name': 'Личное сообщение',
                'verbose_name_plural': 'Личные сообщения',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrivateThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Тема переписки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Личная переписка',
                'verbose_name_plural': 'Личные переписки',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PrivateThreadParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField(blank=True, null=True, verbose_name='Прочитано до')),
            ],
            options={
                'verbose_name': 'Участник ЛС',
                'verbose_name_plural': 'Участники ЛС',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, default='', max_length=200, verbose_name='URL (slug)')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_sticky', models.BooleanField(default=False, verbose_name='Закреплено')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Закрыто')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('is_removed', models.BooleanField(default=False, verbose_name='Удалено (мягко)')),
                ('removed_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда удалено')),
                ('removal_reason', models.TextField(blank=True, verbose_name='Причина удаления темы')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'ordering': ['-is_sticky', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicBookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
            ],
            options={
                'verbose_name': 'Закладка на тему',
                'verbose_name_plural': 'Закладки на темы',
            },
        ),
        migrations.CreateModel(
            name='TopicRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
                ('old_title', models.CharField(max_length=200, verbose_name='Был заголовок')),
                ('new_title', models.CharField(max_length=200, verbose_name='Стал заголовок')),
                ('old_content', models.TextField(verbose_name='Было содержание')),
                ('new_content', models.TextField(verbose_name='Стало содержание')),
                ('edit_reason', models.CharField(blank=True, max_length=500, verbose_name='Причина правки')),
            ],
            options={
                'verbose_name': 'История правок темы',
                'verbose_name_plural': 'История правок тем',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Подписан с')),
            ],
            options={
                'verbose_name': 'Подписка на тему',
                'verbose_name_plural': 'Подписки на темы',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL-slug')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='forum.category', verbose_name='Родительский раздел')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order', 'name'],
            },
        ),
    ]
