# Generated by Django 6.0.3 on 2026-04-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='Заголовок (H1)')),
                ('content', models.TextField(blank=True, help_text='Редактор Summernote. При сохранении HTML очищается bleach (безопасное подмножество тегов).', verbose_name='Содержимое (HTML)')),
            ],
            options={
                'verbose_name': 'Страница «О нас»',
                'verbose_name_plural': 'Страница «О нас»',
                'db_table': 'site_pages_aboutpage',
            },
        ),
        migrations.CreateModel(
            name='ContactsPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='Заголовок (H1)')),
                ('content', models.TextField(blank=True, help_text='Редактор Summernote. При сохранении HTML очищается bleach (безопасное подмножество тегов).', verbose_name='Содержимое (HTML)')),
            ],
            options={
                'verbose_name': 'Страница «Контакты»',
                'verbose_name_plural': 'Страница «Контакты»',
                'db_table': 'site_pages_contactspage',
            },
        ),
        migrations.CreateModel(
            name='PrivacyPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='Заголовок (H1)')),
                ('content', models.TextField(blank=True, help_text='Редактор Summernote. При сохранении HTML очищается bleach (безопасное подмножество тегов).', verbose_name='Содержимое (HTML)')),
            ],
            options={
                'verbose_name': 'Страница «Конфиденциальность»',
                'verbose_name_plural': 'Страница «Конфиденциальность»',
                'db_table': 'site_pages_privacypage',
            },
        ),
        migrations.CreateModel(
            name='RulesPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='Заголовок (H1)')),
                ('content', models.TextField(blank=True, help_text='Редактор Summernote. При сохранении HTML очищается bleach (безопасное подмножество тегов).', verbose_name='Содержимое (HTML)')),
            ],
            options={
                'verbose_name': 'Страница «Правила»',
                'verbose_name_plural': 'Страница «Правила»',
                'db_table': 'site_pages_rulespage',
            },
        ),
    ]
